{% extends "template/layout/memberprofiletemplate.phtml" %}
{% block cpanelcontent  %}
<div class="member-profile-wrapper">
    <a href="#">
        <div class="jumbotron-wrapper">
            <div class="member-profile-thumbnail-wrapper">
                <a href="#">
                    <img class="member-profile-thumbnail-image" src="/assets/images/site/user1.png">
                </a>
            </div>
        </div>
    </a>
    <div> Edit Profile Setting </div>
    <div> Edit Bio  </div>
    <div> Edit Music  </div>
    <div> Edit Video  </div>
</div>
{% endblock %}