{% block jumbotron %}
    <!--img src="/assets/images/slideshow/Free-Hip-Hop-Wallpaper.jpg" class="homeSlide_imgs" title=""-->
    <!--video autoplay>
        <source  type="video/mp4" src="/assets/media/video/vlogcast/Unit_Page_Creation_Tutorial.mp4">
    </video-->
    <div id="s5" class="homeSlide">
        <img class="homeSlide_imgs" alt="{{ siteName }}"
             src="assets/images/slideshow/Free-Hip-Hop-Wallpaper.jpg" />
        <!--img class="homeSlide_imgs" alt="{{ siteName }}"
             src="assets/images/slideshow/marvintdawson_background.png" />
        <img class="homeSlide_imgs" alt="{{ siteName }}"
             src="assets/images/slideshow/logo_url_black_bkground_2500_x_1152.png" /-->
    </div>
<!--script type="text/javascript">
    $('#s5').cycle({
        fx:    'fade',
        pause:  1
    });
</script-->
{% endblock %}