{% extends "template/layout/appcmscpaneltemplate.phtml" %}
{% block cpanelcontent  %}
<div id="cPanPages">
    <h1> {{ pageTitle }}  </h1 >
    <div class="breadcrumb-font"><a href="{{ indexpage }}"><< {{ breadcrumb_index }} Home</a></div>
    <hr>
    <div class="row">
        <div class="col-sm-4 cpanel-thumb-container">
            <a href="{{ themefont }}">
                <i class="fa fa-font fa-5x" aria-hidden="true" ></i>
            </a>
            <div class="cpanel-thumb-label">
                <a href="{{ themefont }}">EDIT FONT</a>
            </div>
        </div>
        <div class="col-sm-4 cpanel-thumb-container">
            <a href="{{ themelayoutcolor }}">
                <i class="fa fa-pencil fa-5x" aria-hidden="true" ></i>
            </a>
            <div class="cpanel-thumb-label">
                <a href="{{ themelayoutcolor }}">EDIT LAYOUT</a>
            </div>
        </div>
        <div class="col-sm-4 cpanel-thumb-container">
            <a href="{{ themepagebkgroundcolor }}">
                <i class="fa fa-paint-brush fa-5x" aria-hidden="true" ></i>
            </a>
            <div class="cpanel-thumb-label">
                <a href="{{ themepagebkgroundcolor }}">BACKGROUND</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}