{% extends "template/layout/basetemplate.phtml" %}
{% block maincontent %}
<div class="corepage-wall-image-cummins-1200-wrapper">
    <img src="../assets/images/clients/cummins/masf_portal1.jpg" class="corepage_wall_image_cummins_1200">
</div>
<div class="main-content">
    <div class="corepage-title">{{ pageTitle }}</div>
    <div class="corepage-content-wrapper">
        {{ pageContent }}
    </div>
</div>
{% endblock %}