<div class="row">
        <div class="tinymce-editor-wrapper">
            <form action="{{ processuploadPageContent }}" method="post" enctype="multipart/form-data"  class="edit-page-editor" name="{{ uploadPageContentFormName }}">
                <label>Page Editor: </label>
                <textarea id="editcorepages" name="editcorepages" title="">{{ pageContent }}</textarea>
                <input type="hidden" name="csrf_token" value="{{ csrftoken }}" >
                <input type="submit" value="SAVE" class="corepages-submit-button" name="corepages_SubmitBtn" />
            </form>
        </div>
</div>