{% extends "template/layout/appcmscpaneltemplate.phtml" %}
{% block cpanelcontent  %}
<div id="cPanPages">
    <h1>{{ pageTitle }}</h1>
    <div class="breadcrumb-font"><a href="{{ indexpage }}"><< {{ breadcrumb_index }} Home</a></div>
    <hr>
    <div class="row">
        <form action="{{ processForm }}" method="post" class="ajax" name="{{ formName }}" >
            <div class="cpan-input-wrapper">
                <h3>PRIMARY EMAIL</h3>
                <div class="form-field-para">Your primary email address is:  {{ currentEmail }}</div>
                <label>Update Primary Email: </label>
                <input type="text" name="user-primary-email" id="user-primary-email" class="input-form-fields" value=" ">
            </div>
            <hr>
            <input type="submit" name="{{ submitButton }}" value="Update Email Info" class="cpan-forms-submit-button" />
        </form>
    </div>
</div>
{% endblock %}