{% extends "template/layout/appcmscpaneltemplate.phtml" %}
{% block cpanelcontent  %}
<div id="cPanPages">
    <h1>{{ pageTitle }}</h1>
    <div class="breadcrumb-font"><a href="{{ indexpage }}"><< {{ breadcrumb_index }} Home</a></div>
    <hr>
    <div class="row">
        <form action="{{ processForm }}" method="post" class="ajax" name="{{ formName }}" >

            <div class="cpan-input-wrapper">
                <h3>STATE</h3>
                <div class="form-field-para">Your home state is:  {{ userstate }}</div>
                <label>Select State: </label>
                <select id="user_state" name="user_state"  class="input-form-fields">
                    <option selected="selected">Choose your state:</option>
                    {% for key, state in states %}
                    <option value="{{ key }}"> {{ state }} </option>
                    {% endfor %}
                </select>
            </div><hr>

            <input type="submit" name="{{ submitButton }}" value="SAVE" class="cpan-forms-submit-button" />
        </form>

    </div>
</div>
{% endblock %}