{% extends "template/layout/appcmscpaneltemplate.phtml" %}
{% block cpanelcontent %}
<div id="cPanPages">
    <h1>{{ pageTitle }} </h1>
    <div class="breadcrumb-font"><a href="{{ indexpage }}"><< {{ breadcrumb_index }} Home</a></div>
    <hr>
    <form action="{{ processaddimageform }}" method="post" class="ajax" >
        <div class="cpan-input-wrapper">

        </div>
        <div class="cpan-input-wrapper">
            <label>Upload Image: </label>
            <input type="file"  name=""
                   class="input-form-fields"  />
        </div>
        <input type="submit" value="Upload Image" class="cpan-forms-submit-button" id="{{ slideshowForm_Submit }}" />
    </form>
</div>
{% endblock %}