{% block maincontent %}
<h3>Welcome To {{ site_name }} </h3>
<div style="padding:12px; font-size:17px;">
    Hello New Member,<br /><br />

    Thank you for registering at {{ site_name }} and joining our community!<br /><br />

    You are almost ready to log into {{ site_name }} after you have successfully completed the activation process using your:<br /><br />

    REGISTERED email address and password.<br /><br />

    Click on the provided link, that we just sent to your email to complete the process.<br /><br />

    Thank you,<br /><br />

    TEAM {{ site_name}} !!
</div>
{% endblock %}