{% extends "template/layout/basetemplate.phtml" %}
{% block maincontent %}
<div class="main-content">
    <div style="padding:12px; font-size:17px;">
        We're Sorry<br /><br />
        Your attempt to login failed.<br /><br />
        Our record's indicate that you have not completed your membership registration.<br /><br />
        Please log into your email account that you registered with and click on the provided link.<br /><br />
    </div>
</div>
{% endblock %}