<!-- START FOOTER CONTAINER -->
<div class="footer-nav">
    <div class="col-sm-4 col-md-4 widget footer-nav-subdiv">
        <h3>HGDLLC.com</h3>
        <p>At Home Grown MusiQ Network LLC we offer web hosting, domain registration for both web and mobile development.</p>
        <p>Visit <a href="http://www.hgdllc.com">HGDLLC.com</a> for your web or mobile solution.</p>
    </div><hr class="footer-hr">

    <div class="col-sm-4 col-md-4 widget footer-nav-subdiv">
        <h3>getMARVELLE CMS</h3>
        <p>getMarvelle is my first original cms project as a Software Engineer. The goal of <a href="http://www.getmarvelle.com">getMarvelle</a> CMS will be to be EASY and SIMPLE to use.
    </div><hr class="footer-hr">

    <div class="col-sm-4 col-md-4 widget footer-nav-subdiv">
         <h3>Looking For Talent</h3>
         <p>Contact me to find out how my skills match your needs.</p>
         <p>Email me: marvintdawson@gmail.com</p>
         <p>Mobile: (770) 530-2929</p>
    </div><hr class="footer-hr">
</div>
<div class="site-footer">
    {{ siteName }} &copy; <?php echo date('Y');?>
    <a href="/">
    </a> is powered by getMarvelle CMS.  getMarvelle CMS is a copyrighted and a registered trademark. The LADDER theme was develop by webmaster
    <a href="http://www.marvintdawson.com">Marvin Dawson</a>. Hosted by Home Grown Musiq Network LLC.
</div>