<footer>
    <!-- START FOOTER NAV WRAPPER -->
    <div class="footer-nav">
        <ul>
            <li><a href="/">{{ siteName }} &copy; <?php echo date('Y');?></a></li>
            <li><a href="/about/index">ABOUT</a></li>
            <li><a href="/products/index">EDUCATION</a></li>
            <li><a href="/services/index">WORK</a></li>
            <li><a href="/contact/index">CONTACT</a></li>
        </ul>
    </div>
    <div class="site-footer">
        {{ siteName }} &copy; <?php echo date('Y');?>
        <a href="/">
        </a> is powered by getMarvelle CMS.  getMarvelle CMS is a copyrighted and a registered trademark. The LADDER theme was develop by webmaster
        <a href="/">Marvin Dawson</a>. Hosted by Home Grown Musiq Network LLC.
    </div>
</footer>