<div class="mast-head">
    <div class="col-xs-12 col-sm-6 col-md-8 logo-wrapper">
        <a href="/">
            <img class="logo" src="../../assets/images/logo.png" alt="HGM Logo">
        </a>
    </div>
    <div class="nav-mobile-button"></div>
    {% include 'template/layout/header_nav.phtml' %}
</div><!-- #end mast head -->
<script type="text/javascript">
    $(".nav-mobile-button").click(function(){
        $(".nav-link-wrapper").slideToggle("slow");
    });
</script>