<head>
    <meta charset="utf-8">
    <meta name ="Keywords" content="{{ siteKeywords }}"/>
    <meta name="description" content="{{ pageDescription }}" />
    <meta name="rating" content="General"/>
    <meta name="ROBOTS" content="All" />
    <meta name="revisit-after" content="7 days" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- stylesheets -->
    <link href="/resources/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" >
    <link href="/resources/font_awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
    <link href="/resources/uikit/css/uikit.min.css" rel="stylesheet" >
    <link href="/resources/css/header.css" rel="stylesheet" >
    <link href="/resources/css/footer.css" rel="stylesheet" >
    <link href="/resources/css/main_content.css" rel="stylesheet" >
    <link href="/resources/css/cpan_form_base.css" rel="stylesheet" >
    <link href="/resources/css/form_base.css" rel="stylesheet" >
    <link href="/resources/css/banners.css" rel="stylesheet" >
    <link href="/resources/css/slide_shows.css" rel="stylesheet" >
    <link href="/resources/css/hgmplayer.css" rel="stylesheet" >
    <link href="/resources/css/radioconsole.css" rel="stylesheet">
    <link href="/resources/css/css/styles.css" rel="stylesheet" >
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">

    <!-- jquery -->
    <script type="text/javascript" src="/resources/js/jquery/jquery-3.1.1.min.js"></script>
    <script type="text/javascript" src="/resources/js/jquery/jquery.validate.js"></script>
    <script type="text/javascript" src="/resources/js/jquery/jquery_function_controllers.js"></script>
    <script type="text/javascript" src="/resources/js/tinymce/js/tinymce/tinymce.min.js"></script>


    <!--script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>


    <!-- js -->
    <script type="text/javascript" src="/resources/js/form_validation.js"></script>
    <script type="text/javascript" src="/resources/js/tinymce_selectors.js"></script>
    <script type="text/javascript" src="/resources/js/jquery/themelayout.js"></script>

    <!--script src='//cdn.tinymce.com/4/tinymce.min.js'></script-->

    <!-- jquery cycle plugin -->
    <!--script type="text/javascript" src="http://malsup.github.com/chili-1.7.pack.js"></script-->
    <script type="text/javascript" src="http://malsup.github.com/jquery.cycle.all.js"></script>

    <!-- fav icon -->
    <link rel="shortcut icon" href="/assets/images/favicon.ico" type="image/x-icon" />
    <link rel="icon" href="/assets/images/favicon.ico" type="image/x-icon" />

    <title>{{ tabTitle }}</title>
</head>