{% extends "template/layout/appcmscpaneltemplate.phtml" %}
{% block cpanelcontent  %}
<div id="cPanPages">
    <h1> {{ pageTitle }}  </h1>
    <div class="breadcrumb-font"><a href="{{ indexpage }}"><< {{ breadcrumb_index }} Home</a></div>
    <hr>
    <div class="row">
        <div class="col-sm-4 cpanel-thumb-container">
            <a href="{{ addgallery }}">
                <i class="fa fa-plus fa-5x" aria-hidden="true" ></i>
            </a>
            <div class="cpanel-thumb-label">
                <a href="{{ addgallery }}">ADD GALLERY</a>
            </div>
        </div>
        <div class="col-sm-4 cpanel-thumb-container">
            <a href="{{ editgallery }}">
                <i class="fa fa-pencil fa-5x" aria-hidden="true" ></i>
            </a>
            <div class="cpanel-thumb-label">
                <a href="{{ editgallery }}">EDIT GALLERY</a>
            </div>
        </div>
        <div class="col-sm-4 cpanel-thumb-container">
            <a href="{{ deletegallery }}">
                <i class="fa fa-trash fa-5x" aria-hidden="true" ></i>
            </a>
            <div class="cpanel-thumb-label">
                <a href="{{ deletegallery }}">DELETE GALLERY</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}