<div class="core-ads-lower-wrapper">
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- cpanel-ad-banner -->
    <ins class="adsbygoogle"
         style="display:block"
         data-ad-client="ca-pub-3000506446152743"
         data-ad-slot="4361994840"
         data-ad-format="auto"></ins>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
</div>