{% extends "template/layout/basetemplate.phtml" %}
{% block maincontent %}
<div class="corepage-wall-image-aerometals-1200-wrapper">
    <img src="../assets/images/clients/homegrownmusiq/hgm_homepage.jpg" class="corepage_wall_image">
</div>
<div class="main-content">
    <div class="corepage-title">{{ pageTitle }}</div>
    <div class="corepage-content-wrapper">
        {{ pageContent }}
    </div>
</div>
{% endblock %}