<ul>
    <li>
        <div id="cpanel-menu-category1" article="{{ cmsmusicindex }}">
            <a href="{{ cmsmusicindex }}">MUSIC</a>
        </div>
        <div id="admin-menu-category1">
            <ul>
                <li class="navItem" article="{{ addcd }}">
                    <a href="{{ addcd }}">Add CD</a>
                </li>
                <li class="navItem" article="{{ addmusic }}">
                    <a href="{{ addmusic }}">Add Music</a>
                </li>
                <li class="navItem" article="{{ editmusic }}">
                    <a href="{{ editmusic }}"> Edit Music</a>
                </li>
                <li class="navItem" article="{{ deletemusic }}">
                    <a href="{{ deletemusic }}">Delete Music</a>
                </li>
            </ul>
        </div>
    </li>
    <li>
        <div id="cpanel-menu-category2" article="{{ videoindex }}">
            <a href="{{ videoindex }}">VIDEOS</a>
        </div>
        <div id="admin-menu-category2">
            <ul>
                <li class="navItem" article="{{ addvideo }}">
                    <a href="{{ addvideo }}">Add Video</a>
                </li>
                <li class="navItem" article="{{ editvideo  }}">
                    <a href="{{ editvideo  }}">Edit Video</a>
                </li>
                <li class="navItem" article="{{ deletevideo }}">
                    <a href="{{ deletevideo }}">Delete Video</a>
                </li>
            </ul>
        </div>
    </li>
    <li>
        <div id="cpanel-menu-category3" article="{{ cmsvmindex }}">
            <a href="{{ cmsvmindex }}">VIRTUAL MANAGER</a>
        </div>
        <div id="admin-menu-category3">
            <ul>
                <li class="navItem" article="{{ fanstats }}">
                    <a href="{{ fanstats }}">Fans Stats</a>
                <li class="navItem" article="{{ trackstats }}">
                    <a href="{{ trackstats }}">Track Stats</a>
                </li>
            </ul>
        </div>
    </li>

    <li>
        <div id="cpanel-menu-category4" article="{{ slideshowindex }}">
            <a href="{{ slideshow }}">SLIDE SHOW</a>
        </div>
        <div id="admin-menu-category4">
            <ul>
                <li class="navItem" article="{{ slideshow }}">
                    <a href="{{ slideshow }}">Edit Slides</a>
                </li>
            </ul>
        </div>
    </li>

    <li>
        <div id="cpanel-menu-category5" article="{{ corepageindex }}">
            <a href="{{ corepages }}">PAGES</a>
        </div>
        <div id="admin-menu-category5">
            <ul>
                <li class="navItem" article="{{ corepages }}">
                    <a href="{{ corepages }}">Edit</a>
                </li>
            </ul>
        </div>
    </li>

    <li>
        <div id="cpanel-menu-category6" article="{{ themeindex }}">
            <a href="{{ themeindex }}">THEME</a>
        </div>
        <div id="admin-menu-category6">
            <ul>
                <li class="navItem" article="{{ themepagebkgroundcolor }}">
                    <a href="{{ themepagebkgroundcolor }}">Page Color</a>
                </li>
                <li class="navItem" article="{{ themefont }}">
                    <a href="{{ themefont }}">Font Style</a>
                </li>
                <li class="navItem" article="{{ themelayoutcolor }}">
                    <a href="{{ themelayoutcolor }}">Layout Color</a>
                </li>
            </ul>
        </div>
    </li>

    <li>
        <div id="cpanel-menu-category7" article="{{ contactentries }}">
            <a href="{{ contactentries }}">CONTACTS</a>
        </div>
        <div id="admin-menu-category7">
            <ul>
                <li class="navItem" article="{{ contactentries }}">
                    <a href="{{ contactentries }}">Requests</a>
                </li>
            </ul>
        </div>
    </li>

    <li>
        <div id="cpanel-menu-category8" article="{{ profilenotifications }}">
            <a href="{{ profilenotifications }}">SETTINGS</a>
        </div>
        <div id="admin-menu-category8">
            <ul>
                <li class="navItem" article="{{ profilenotifications }}">
                    <a href="{{ profilenotifications }}">  Notifications </a>
                </li>
            </ul>
        </div>
    </li>
    <li>
        <div id="cpanel-menu-category9" article="{{ userprofileindex }}">
            <a href="{{ userprofileindex }}">USER PROFILE</a>
        </div>
        <div id="admin-menu-category9">
            <ul>
                <li class="navItem" article="{{ editaddress }}">
                    <a href="{{ editaddress }}"> Edit Address </a>
                </li>
                <li class="navItem" article="{{ editemail }}">
                    <a href="{{ editemail }}">  Edit Email </a>
                </li>
                <li class="navItem" article="{{ editphone }}">
                    <a href="{{ editphone }}">  Edit Phone </a>
                </li>
            </ul>
        </div>
    </li>

    <li>
        <div id="cpanel-menu-category10" article="{{ cmscontbrdindex }}">
            <a href="{{ cmscontbrdindex }}">CONTROL BOARD<a/>
        </div>
        <div id="admin-menu-category10">
            <ul>
                <li class="navItem" article="{{ controlboard }}">
                    <a href="{{ controlboard }}">Mixer Board</a>
                </li>
                <li class="navItem" article="{{ soundeffects }}">
                    <a href="{{ soundeffects }}">Sound Xfs</a>
                </li>
            </ul>
        </div>
    </li>

</ul>