{% extends "template/layout/appcmscpaneltemplate.phtml" %}
{% block cpanelcontent  %}
<div id="cPanPages">
    <h1> {{ pageTitle }}  </h1>
    <div class="breadcrumb-font"><a href="{{ indexpage }}"><< {{ breadcrumb_index }} Home</a></div>
    <hr>
    <div class="row">
        <div class="col-sm-3 cpanel-thumb-container">
            <a href="{{ addsocialmedia }}">
                <i class="fa fa-plus fa-5x" aria-hidden="true" ></i>
            </a>
            <div class="cpanel-thumb-label">
                <a href="{{ addsocialmedia }}">ADD SOCIAL</a>
            </div>
        </div>
        <div class="col-sm-3 cpanel-thumb-container">
            <a href="{{ editsocialmedia }}">
                <i class="fa fa-pencil fa-5x" aria-hidden="true" ></i>
            </a>
            <div class="cpanel-thumb-label">
                <a href="{{ editsocialmedia }}">EDIT SOCIAL</a>
            </div>
        </div>
        <div class="col-sm-3 cpanel-thumb-container">
            <a href="{{ deletesocialmedia }}">
                <i class="fa fa-trash fa-5x" aria-hidden="true" ></i>
            </a>
            <div class="cpanel-thumb-label">
                <a href="{{ deletesocialmedia }}">DELETE SOCIAL</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}