{% extends "template/layout/basetemplate.phtml" %}
{% block maincontent %}
<div class="corepage-wall">
    <img src="../assets/images/slideshow/html_background.jpg" class="corepage_wall_image">
</div>
<div class="main-content">
    <div class="corepage-title">{{ pageTitle }}</div>
    <div class="corepage-content-wrapper">
        <p>I have developed web sites using HTML & CSS for over 10 years, while adding PHP and MySQL in the past 8 years.</p>
        <p><em>&quot; I am totally intrigued with the idea of creating something that the world would see, I continue to add various programs and design tools to my arsenal of creation&quot;</em>.</p>
        <h3 class="para-font-color">My Story....</h3>
        <p>My first website was a mess.  I created it in 1997, where I started my online Christian clothing line at "jita.com" or J.I.T.A. an acronym for Jesus Is The Answer Clothing. </p>
        <p>Well back then it was awesome to me.  I mean from a web design perspective it was really bad. That was painfully obvious to me when I contacted a Yahoo customer service rep to ask for some technical advice and was told that my website was horrible.  Not sure if that was a seg way into a sales pitch? </p>
        <p>Every container on the site consisted of a text box specifically place and a img container (not a div) specifically.  It took me forever to make that web site, hahaha. I laugh now looking back, but at the time, man I was a BAD man you couldn't tell me nothing, I had a web site. </p>
        <p>Committed to learning I never gave up practicing, researching, and growing.  In 2009 I embarked on a new web venture with the idea that I would create a web community with very similar functionality as, MySpace, Facebook, and Twitter.</p>
        <h2 class="para-font-color">Why PHP?</h2>
        <h3 class="para-font-color">The Birth of HomeGrownMusiq,com, My First PHP Site!</h3>
        <p><img src="../assets/images/hgmLogo2_whitebackground.jpg" width="73" height="75" alt="hgmLogo" />
            <a href="http://www.homegrownmusiq.com">HomeGrownMusiq.com</a> had a lot of energy out the gate. Back then people were starting to sign up and wait, I can't make that many web pages statically. </p>
        <h3 class="para-font-color">The Dilemma</h3>
        <p>I created 100 hundred static web pages and now the page header is off on this page.  Yup, I copied and pasted it on all the other pages, so all of those pages are off too, nice. So fix the error and copy it into the other hundred pages. This is taking forever I need help. Artist are emailing me asking when can they get access to their page?</p>
        <p>Lets just say it can't be done statically.  HELLO WORLD!!! </p>
        <p>In comes PHP and MySQL to save the day. We shut the site down and I embarked on the task of working a regular 9 to 5, while running a home studio, and learning PHP and MySQL. </p>
        <p>I read and researched  dynamic web programming langauges and ended up being even more confused. </p>
        <p>What is C? Is C+ different from C? Is C++ better? Do I need ASP.net? Learn PHP - What is that? Capture your data with MySQL, huh? I almost cried from the huge amount of free information out there regarding programming and open source info. </p>
        <p>In the end I settled on PHP, and worked on redesigning the site, dropping Yahoo's Sitekiller and learning how to use Adobe's Dreamweaver IDE for the code hinting. Which I like to say back then code hinting and syntax error hightlighting could not be taken lightly in dynamic programming.</p>
        <p>I felt like I was in school again, while working, recording music and helping other people with their websites. I literally had no time for HomeGrownMusiq.com. </p>
        <p>None the less the joy of having the understanding of dynamic programming was a personal gain that has given me a great level of self gratification, and has allow me to help others while learning and presented new experiences.</p>
        <p>Fast forward to today and I have gained new experience using a variety of other programming languages such as: PHP with a OOP focus, MySQL, ActionScript 3.0, JavaScript, Linux, Apache, Apache PhoneGap, Apache Ionic, NodeJS, MongoDB, Express, Angular2, Java, ASP.NET, jQuery, AJAX, XML, JSON, Python3. Web design and programming in still exciting to me as it was back in 1997. </p>
        <p>As of 2016 heading into 2017 I started developing my own CMS template as a hobby.  I named it <a href="http://www.getmarvelle.com">getMarvelle</a>, you can visit it, and for now all I have is a landing page unfortunately with all of the other stuff I have going on.</p>
        <p>Look around, click on some of the other sites and applications I've worked on.</p>
        <p>Thanks for reading....</p>
    </div>
</div>
{% endblock %}