{% extends "template/layout/basetemplate.phtml" %}
{% block maincontent %}
<div class = "main-content-tier1-wrapper" >
    <section class="tier1">
        <div class="container">
            <div class="row">
                <div class="col-md-12 welcome">
                    <h1>Portfolio</h1>
                </div>
                <!-- START CORPORATE THUMBNAILS -->
                <div class="col-md-12  index-top-row">
                    <h2 class="freelance-text-h2">ENCOMPASS DIGITAL MEDIA INC</h2>
                    <h4>U.S. Department Of Defense</h4>
                    <div class="col-sm-4 col-md-4">
                        <div class="thumbnail work-thumbnail">
                            <a href="/portfolioclients/encompassdigitalmedia">
                                <div id="portfolio-thumbnail-img-1" class="portfolio-thumbnail-img"></div>
                                <!--img class="portfolio-thumbnail-img" src="/assets/images/clients/encompass/encompass_logo2.jpeg" alt="..."></a-->
                            <div class="caption">
                                <h3>DVIDSHUB.NET</h3>
                                <p>Zend Framework application for U.S. military personel and branches.</p>
                                <p>
                                    <a href="/portfolioclients/encompassdigitalmedia" class="btn btn-primary" role="button">More</a>
                                    <!--a href="#" class="btn btn-default" role="button"></a-->
                                </p>
                            </div>
                        </div><!-- end thumbnail one -->
                    </div>
                </div><!-- #end col-md-12 -->
            </div><!--  end row -->
        </div><!-- end container -->
    </section><!-- end section -->

    <section class="tier1 bg-asbesto">
        <div class="container">
            <div class="row">
                <!-- START CORPORATE THUMBNAILS -->
                <div class="col-md-12  index-top-row">
                    <h2 class="freelance-text-h2">CUMMINS INC</h2>
                    <div class="col-sm-4 col-md-4">
                        <div class="thumbnail work-thumbnail">
                            <a href="/portfolioclients/cummins">
                                <div id="portfolio-thumbnail-img-2" class="portfolio-thumbnail-img"></div>
                            <div class="caption">
                                <h3>M.A.S.F PORTAL</h3>
                                <p>Creation of a 'ORIGINAL' demo called "Material and Shop Floor (M.a.S.F)" Portal for Cummins Inc.</p>
                                <p>
                                    <a href="/portfolioclients/cummins" class="btn btn-primary" role="button">More</a>
                                    <!--a href="#" class="btn btn-default" role="button"></a-->
                                </p>
                            </div>
                        </div><!-- end thumbnail one -->
                    </div>
                </div><!-- #end col-md-12 -->
            </div><!--  end row -->
        </div><!-- end container -->
    </section><!-- end section -->

    <section class="tier2 bg-cloud">
        <div class="row">
                <div class="homepage-index-top-row">
                    <h2 class="freelance-text-h2">ECREATIVEWORKS</h2>
                    <div class="col-sm-4 col-md-4">
                        <div class="thumbnail work-thumbnail">
                            <div id="portfolio-thumbnail-img-4" class="portfolio-thumbnail-img"></div>
                            <div class="caption">
                                <h3>BOULDEN COMPANY</h3>
                                <p>Powered by CMS Made Simple and Wordpress</p>
                                <p><a href="/portfolioclients/ecwboulden" class="btn btn-primary" role="button">More</a>
                                    <a href="http://www.bouldencompany.com" class="btn btn-default" role="button">Visit Live Site</a>
                                </p>
                            </div>
                        </div><!-- end thumbnail one -->
                    </div>

                    <div class="col-sm-4 col-md-4">
                        <div class="thumbnail work-thumbnail">
                            <div id="portfolio-thumbnail-img-7" class="portfolio-thumbnail-img"></div>
                            <h3>CONDENSOR AND CHILLER</h3>
                                <p>Powered by osCommerce</p>
                                <p></p>
                                <p><a href="/portfolioclients/ecwccstubes" class="btn btn-primary" role="button">More</a>
                                    <a href="http://www.ccs-tubes.com" class="btn btn-default" role="button">Visit Live Site</a></p>
                        </div>
                    </div><!-- end thumbnail two -->

                    <div class="col-sm-4 col-md-4">
                        <div class="thumbnail work-thumbnail">
                            <div id="portfolio-thumbnail-img-8" class="portfolio-thumbnail-img"></div>
                            <div class="caption">
                                <h3>AERO METALS</h3>
                                <p>Powered by CMS Made Simple</p>
                                <p>
                                    <a href="/portfolioclients/ecwaerometals" class="btn btn-primary" role="button">More</a>
                                    <a href="http://www.aerometals.com" class="btn btn-default" role="button">Visit Live Site</a>
                                </p>
                            </div>
                        </div>
                    </div><!-- end thumbnail three -->
                </div><!-- #end ecreative row 1-->
        </div>

        <div class="row">
            <div class="homepage-index-second-row">
                    <div class="col-sm-4 col-md-4">
                        <div class="thumbnail work-thumbnail">
                            <div id="portfolio-thumbnail-img-9" class="portfolio-thumbnail-img"></div>
                            <div class="caption">
                                <h3>QUALITY AIR SERVICES</h3>
                                <p>Powered by CMS Made Simple</p>
                                <p>
                                    <a href="/portfolioclients/ecwqualityairservices" class="btn btn-primary" role="button">More</a>
                                    <a href="http://www.quality-air-services.net" class="btn btn-default" role="button">Visit Live Site</a>
                                </p>
                            </div>
                        </div><!-- end thumbnail one -->
                    </div>

                    <div class="col-sm-4 col-md-4">
                        <div class="thumbnail work-thumbnail">
                            <div id="portfolio-thumbnail-img-5" class="portfolio-thumbnail-img"></div>
                            <div class="caption">
                                <h3>LEECYN COMPANY</h3>
                                <p>Powered by CMS Made Simple</p>
                                <p>
                                    <a href="/portfolioclients/ecwleecyn" class="btn btn-primary" role="button">More</a>
                                    <a href="http://www.leecyn.com" class="btn btn-default" role="button">Visit Live Site</a>
                                </p>
                            </div>
                        </div>
                    </div><!-- end thumbnail two -->

                    <div class="col-sm-4 col-md-4">
                        <div class="thumbnail work-thumbnail">
                            <div id="portfolio-thumbnail-img-6" class="portfolio-thumbnail-img"></div>
                            <div class="caption">
                                <h3>GREENVILLE TOOL</h3>
                                <p>Powered by CMS Made Simple</p>
                                <p>
                                    <a href="/portfolioclients/ecwgreenvilletool" class="btn btn-primary" role="button">More</a>
                                    <a href="http://www.gtd.com" class="btn btn-default" role="button">Visit Live Site</a>
                                </p>
                            </div>
                        </div>
                    </div><!-- end thumbnail three -->
            </div>
        </div><!-- #end ecreative row 2 -->

    </section>

    <!-- START FREELANCE -->
    <section class="tier3">
        <div class="container">
            <!-- START FREELANCE THUMBNAILS ROW 1 -->
            <div class="row">
                <div class="col-md-12">
                    <h2 class="freelance-text-h2">FREELANCE</h2>
                    <div class="col-sm-4 col-md-4">
                        <div class="thumbnail work-thumbnail">
                            <div id="portfolio-thumbnail-img-10" class="portfolio-thumbnail-img"></div>
                            <div class="caption">
                                <h3>Prep U Tracker eLearning</h3>
                                <p>Powered by getMarvelle CMS (beta).</p>
                                <p>
                                    <a href="/portfolioclients/preputracker" class="btn btn-primary" role="button">More</a>
                                    <a href="http://www.preputracker.com" class="btn btn-default" role="button">Visit Site</a>
                                </p>
                            </div>
                        </div>
                    </div><!-- end col-sm-4 -->

                    <div class="col-sm-4 col-md-4">
                        <div class="thumbnail work-thumbnail">
                            <div id="portfolio-thumbnail-img-11" class="portfolio-thumbnail-img"></div>
                            <div class="caption">
                                <h3>Burgin Construction LLC</h3>
                                <p>Powered by getMarvelle CMS (beta).</p>
                                <p>
                                    <a href="/portfolioclients/burginconstruction" class="btn btn-primary" role="button">More</a>
                                    <a href="http://www.burginconstructionllc.com" class="btn btn-default" role="button">Visit Site</a>
                                </p>
                            </div>
                        </div>
                    </div><!-- end thumbnail two -->

                    <div class="col-sm-4 col-md-4">
                        <div class="thumbnail work-thumbnail">
                            <div id="portfolio-thumbnail-img-12" class="portfolio-thumbnail-img"></div>
                            <div class="caption">
                                <h3>Mattress & Things LLC</h3>
                                <p>Powered by getMarvelle CMS (beta).</p>
                                <p>
                                    <a href="/portfolioclients/mattressandthings" class="btn btn-primary" role="button">More</a>
                                    <a href="http://www.matressandthings.com" class="btn btn-default" role="button">Visit Site</a>
                                </p>
                            </div>
                        </div>
                    </div><!-- end thumbnail two -->

                </div><!-- #end container -->
            </div><!-- /end row -->
            <div class="row">
                <div class="col-md-12">
                    <div class="col-sm-4 col-md-4">
                        <div class="thumbnail work-thumbnail">
                            <div id="portfolio-thumbnail-img-3" class="portfolio-thumbnail-img"></div>
                            <div class="caption">
                                <h3>KingBiggie.com</h3>
                                <p>Powered by getMarvelle</p>
                                <p>
                                    <a href="/portfolioclients/kingbiggie" class="btn btn-primary" role="button">More</a>
                                    <a href="http://www.kingbiggie.com" class="btn btn-default" role="button">Visit Live Site</a>
                                </p>
                            </div>
                        </div><!-- end thumbnail one -->
                    </div>
                    <div class="col-sm-4 col-md-4">
                        <div class="thumbnail work-thumbnail">
                            <div id="portfolio-thumbnail-img-13" class="portfolio-thumbnail-img"></div>
                            <div class="caption">
                                <h3>HomeGrownMusiQ</h3>
                                <p>Powered by getMarvelle</p>
                                <p>
                                    <a href="/portfolioclients/homegrownmusiq" class="btn btn-primary" role="button">More</a>
                                    <a href="http://www.homegrownmusiq.com" class="btn btn-default" role="button">Visit Live Site</a>
                                </p>
                            </div>
                        </div><!-- end thumbnail one -->
                    </div>
                    <div class="col-sm-4 col-md-4">
                        <div class="thumbnail work-thumbnail">
                            <div id="portfolio-thumbnail-img-14" class="portfolio-thumbnail-img"></div>
                            <div class="caption">
                                <h3>WhosLaundry.com</h3>
                                <p>Powered by getMarvelle</p>
                                <p>
                                    <a href="/portfolioclients/whoslaundry" class="btn btn-primary" role="button">More</a>
                                    <a href="http://www.whoslaundry.com" class="btn btn-default" role="button">Visit Live Site</a>
                                </p>
                            </div>
                        </div><!-- end thumbnail one -->
                    </div>
                </div><!-- #end ecreative row 2 -->
            </div>
        </div>
    </section>

    <!-- START MOBILE APPS THUMBNAILS -->
    <section class="tier4 bg-carrot">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="freelance-text-h2">MOBILE APPS</h2>
                    <div class="col-sm-4 col-md-4">
                        <div class="thumbnail work-thumbnail">
                            <div id="portfolio-thumbnail-img-13" class="portfolio-thumbnail-img"></div>
                            <div class="caption">
                                <h3>HGM Radio APP</h3>
                                <p>App designed using Apache Cordova's Phonegap on a MEAN Stack.</p>
                                <p>
                                    <a href="/portfolioclients/homegrownmusiqmobile" class="btn btn-primary" role="button">More</a>
                                    <a href="http://www.homegrownmusiq.com" class="btn btn-default" role="button">Get App</a>
                                </p>
                            </div>
                        </div><!-- end thumbnail one -->
                    </div>

                    <div class="col-sm-4 col-md-4">
                        <div class="thumbnail work-thumbnail">
                            <div id="portfolio-thumbnail-img-14" class="portfolio-thumbnail-img"></div> <div class="caption">
                                <h3>WHO'S LAUNDRY APP</h3>
                                <p>App designed using Apache Cordova's Phonegap on a MEAN Stack.</p>
                                <p>
                                    <a href="/portfolioclients/whoslaundrymobile" class="btn btn-primary" role="button">More</a>
                                    <a href="http://www.whoslaundry.com" class="btn btn-default" role="button">Get App</a>
                                </p>
                            </div>
                        </div>
                    </div><!-- end thumbnail two -->
                </div><!-- #end container -->
            </div><!-- #end row -->
        </div>
    </section>
</div >
{% endblock %}