{% extends "template/layout/basetemplate.phtml" %}
{% block maincontent %}
    <div class="forgotpassword-form-wrapper">
        <div>
            {{ pageContent }}
        </div><br>

        <!-- Start Form wrapper -->
        <form method="post" action="{{ processform }}" name="{{ formName }}">

            <input type="hidden" name="csrf_token" value="{{ csrftoken }}" >

            <div class="form_fields_wrapper">
                <label class="input-field-label-font">Email:</label>
                <input type="text" name="regEmail_1"
                       class="input-form-fields" title="Email" >
            </div><br>

            <div class="submit-button-div">
                <input type="submit" value="Submit" name="{{ submitbutton }}" >
            </div>
        </form>
    </div><!-- #end form wrapper -->
{% endblock %}