{% extends "template/layout/homepagetemplate.phtml" %}
{% block maincontent %}
<!-- Start Body Content -->
<section class="bg-tan">
    <div class="row">
        <div class="homepage-wall">
            <img src="../assets/images/slideshow/html_background.jpg" class="homeSlide_imgs">
        </div>
    </div><!-- /end row -->
</section><!--  /end section -->

<div class="myphoto-parallax"></div>

<!-- START MY Photo area -->
<section class="bg-cloud">
    <div class="row">
        <div class="myPhoto">
            <div class="homePagePic">
                <img src="../assets/images/selfportraits/mdApril2016_2.jpg" class="homePagePic" alt="">
            </div>
            <div class="homePage-BriefSummary">
                <p>
                    I'm a Senior Web Developer / Software Engineer.
                    I develop and design responsive websites and mobile apps. <br> I currently work as a freelance developer.
                </p>
            </div>
            <div class="moreAbout-Me">
                <span><a href="#about-me">MORE ABOUT ME</a></span>
            </div>
        </div>
    </div>
</section><!--  /end section -->

<div class="recent-work-parallax"></div>

<section class="bg-porcelain">
    <div class="row">
        <div class="homepage-index-top-row">
            <h2 class="section-h2">RECENT WORK</h2>
            <div class="col-sm-4 col-md-4">
                <div class="thumbnail work-thumbnail">
                    <div id="portfolio-thumbnail-img-1" class="portfolio-thumbnail-img"></div>
                    <div class="caption">
                        <h3>DVIDSHUB.net</h3>
                        <p>Powered by Zend Framework</p>
                        <p><a href="/portfolioclients/encompassdigitalmedia" class="btn btn-primary" role="button">More</a>
                            <a href="http://www.dvidshub.net" class="btn btn-default" role="button">Visit Live Site</a>
                        </p>
                    </div>
                </div>
            </div><!-- /end thumbnail one -->

            <div class="col-sm-4 col-md-4">
                <div class="thumbnail work-thumbnail ">
                    <div id="portfolio-thumbnail-img-2" class="portfolio-thumbnail-img"></div>
                    <div class="caption">
                        <h3>CUMMINS INC</h3>
                        <p>Original Internal Application</p>
                        <p>
                            <a href="/portfolioclients/cummins" class="btn btn-primary" role="button">More</a>
                        </p>
                    </div>
                </div>
            </div><!-- /end thumbnail two -->
            <div class="col-sm-4 col-md-4">
                <div class="thumbnail work-thumbnail">
                    <div id="portfolio-thumbnail-img-3" class="portfolio-thumbnail-img"></div>
                    <div class="caption">
                        <h3>KING BIGGIE</h3>
                        <p>Powered by getMarvelle</p>
                        <p><a href="/portfolioclients/kingbiggie" class="btn btn-primary" role="button">More</a>
                            <a href="http://www.kingbiggie.com" class="btn btn-default" role="button">Visit Live Site</a>
                        </p>
                    </div>
                </div>
            </div><!-- /end thumbnail three -->

        </div><!-- /end index-top-row -->

        <div class="homepage-index-second-row">
            <div class="col-sm-4 col-md-4">
                <div class="thumbnail work-thumbnail">
                    <div id="portfolio-thumbnail-img-4" class="portfolio-thumbnail-img"></div>
                    <div class="caption">
                        <h3>BOULDEN COMPANY</h3>
                        <p>Powered by CMS Made Simple and Wordpress</p>
                        <p><a href="/portfolioclients/ecwboulden" class="btn btn-primary" role="button">More</a>
                            <a href="http://www.bouldencompany.com" class="btn btn-default" role="button">Visit Live Site</a>
                        </p>
                    </div>
                </div><!-- end thumbnail one -->
            </div>

            <div class="col-sm-4 col-md-4">
                <div class="thumbnail work-thumbnail">
                    <div id="portfolio-thumbnail-img-5" class="portfolio-thumbnail-img"></div>
                    <div class="caption">
                        <h3>LEECYN COMPANY</h3>
                        <p>Powered by CMS Made Simple</p>
                        <p>
                            <a href="/portfolioclients/ecwleecyn" class="btn btn-primary" role="button">More</a>
                            <a href="http://www.leecyn.com" class="btn btn-default" role="button">Visit Live Site</a>
                        </p>
                    </div>
                </div>
            </div><!-- end thumbnail two -->

            <div class="col-sm-4 col-md-4">
                <div class="thumbnail work-thumbnail">
                    <div id="portfolio-thumbnail-img-6" class="portfolio-thumbnail-img"></div>
                    <div class="caption">
                        <h3>GREENVILLE TOOL</h3>
                        <p>Powered by CMS Made Simple</p>
                        <p>
                            <a href="/portfolioclients/ecwgreenvilletool" class="btn btn-primary" role="button">More</a>
                            <a href="http://www.gtd.com" class="btn btn-default" role="button">Visit Live Site</a>
                        </p>
                    </div>
                </div>
            </div><!-- /end thumbnail three -->
        </div><!-- /end index-second-row -->
    </div>
</section>

<div class="skills-parallax"></div>

<!-- Start Skills -->
<section class="skillsWrapper">
    <div class="row skills-experience">
        <div class="index-top-row">
            <div class="section-h2">SKILLS</div>
            <div class="col-sm-4 col-md-4">
                <div class="skills-thumbnail">
                    <img src="" alt="">
                    <div class="caption">
                        <div class="fa-icon-wrapper">
                            <i class="fa fa-html5 fa-5x"></i><i class="fa fa-css3 fa-5x"></i>
                        </div>
                        <h3>HTML5 + CSS3 / Front End</h3>
                        <p>
                            Capable of demonstrating skills in writing and editing HTML5 and CSS3 <i class="fa fa-css3"></i>.
                        </p>
                    </div>
                </div><!-- end thumbnail one -->
            </div>

            <div class="col-sm-4 col-md-4">
                <div class="skills-thumbnail">
                    <div class="caption">
                        <div class="fa-icon-wrapper">
                            <i class="fa fa-github fa-5x"></i>
                        </div>
                        <h3>Version Control</h3>
                        <p></p>
                        <p>
                            Implement version control using GIT & Mercurial in a multi dev environment.
                        </p>
                    </div>
                </div>
            </div><!-- end thumbnail two -->

            <div class="col-sm-4 col-md-4">
                <div class="skills-thumbnail">
                    <img src="" alt="">
                    <div class="caption">
                        <div class="fa-icon-wrapper">
                            <i class="fa fa-linux fa-5x"></i>
                        </div>
                        <h3>Linux</h3>
                        <p></p>
                        <p>
                            Knowledgeable of Debian / Linux commands in a dev environment.
                        </p>
                    </div>
                </div>
            </div><!-- end thumbnail three -->
        </div><!-- #end ecreative row 2 -->
    </div><!-- #end row -->

    <div class="row skills-experience">
        <div class="index-second-row">
            <div class="col-sm-4 col-md-4">
                <div class="skills-thumbnail">
                    <img src="" alt="">
                    <div class="caption">
                        <div class="fa-icon-wrapper">
                            <i class="fa fa-code fa-5x"></i>
                        </div>
                        <h3>Server-Side / Back End</h3>
                        <p>
                            Knowledge of various back end languages: PHP, NodeJS, Java.
                        </p>
                    </div>
                </div><!-- end thumbnail one -->
            </div>

            <div class="col-sm-4 col-md-4">
                <div class="skills-thumbnail">
                    <img src="" alt="">
                    <div class="caption">
                        <div class="fa-icon-wrapper">
                            <i class="fa fa-android fa-5x"></i>
                        </div>
                        <h3>App Design / Android</h3>
                        <p></p>
                        <p>
                            Design mobile apps using Adobe CC, Apache Cordova, Mobile Angular UI.
                        </p>
                    </div>
                </div>
            </div><!-- end thumbnail two -->

            <div class="col-sm-4 col-md-4">
                <div class="skills-thumbnail">
                    <img src="" alt="">
                    <div class="caption">
                        <div class="fa-icon-wrapper">
                            <i class="fa fa-database fa-5x"></i>
                        </div>
                        <h3>Data</h3>
                        <p></p>
                        <p>
                            Possess knowledge of MySQL, and MongoDB for data capturing.
                        </p>
                    </div>
                </div>
            </div><!-- end thumbnail three -->
        </div><!-- #end ecreative row 2 -->
    </div><!-- #end row -->
</section><!--  #end section -->

<div class="about-me-parallax"></div>

<!-- Start About Me -->
<section class="aboutMeWrapper">
    <div class="row">
        <div class="col-md-12">
            <div id="about-me" class="section-h2">About Me</div>
            <div class="homePagePic">
                <img src="../assets/images/selfportraits/mdApril2016_2.jpg" class="homePagePic" alt="">
            </div>
            <div class="homePage-MoreAboutMe">
                <h3>Senior Web Developer / Software Engineer</h3>
                <p>
                    I am a two fold developer that sees the big picture to maxmize the bottom line.
                    Having over 12 years of Supply Chain with a focus on root cause analysis and LEAN manufacturing,
                    which gives me the ability to better understand the UI for the end user.
                    During my time in Supply Chain, I worked as a freelance developer, learning various programming languages.
                </p>
                <p>
                    My friends say I am smart, easy going, and business focus. My fiance would say I am passionate
                    about web designs and programming.  Being optimistic I believe that there is always a silver lining.
                    My ambitious nature gives me a keen sense of business which translates into success.
                </p>
                <p>
                    When I am not head first in the digital world via new applications or reading books.  I have tunnel vision while playing Call of Duty.  I own
                    all the games.  XBOX game consoles are my preferred play station (for now).  In my down time I am researching new music and helping
                    independent hip hop artists, as a production engineer, using Pro Tools.
                </p>
            </div>
            <div class="moreAbout-Me">
                <span><a href="/assets/resume/mdrez_gptx_6_2017.pdf">DOWNLOAD MY RESUME</a></span>
            </div>
        </div>
    </div><!-- #end row -->
</section>
{% endblock %}