{% extends "template/layout/form_tpl.phtml" %}
{% block mainformcontent %}
    <div class="standard-form-wrapper">
        <!-- Start Form wrapper -->
        <form method="post" action="{{ processform }}" name="{{ formName }}" onsubmit="return validateLoginForm(this)">

            <input type="hidden" name="csrf_token" value="{{ csrftoken }}" >

            <div class="form_fields_wrapper">
                <label class="input-field-label-font">Email:</label>
                <input type="text" name="regMem_E1" id="regMem_E1"
                       class="input-form-fields" title="Email" >
                <!--div id="gif-div">hi</div-->
            </div>


            <div class="form_fields_wrapper">
                <label class="input-field-label-font">Password:</label>
                <input type="password" name="regMem_Pw" id="regMem_Pw"
                       class="input-form-fields" title="Password" >
            </div><br>

            <div class="form_fields_wrapper">
                <label class="input-field-label-font" for="regRemember">
                    <input type="checkbox" name="regRemember" id="regRemember">Remember Me
                </label>
            </div>

            <div class="submit-button-div">
                <input type="submit" name="{{ submitbutton }}" id="loginForm_Submit" value="SUBMIT"  >
            </div>
        </form><br>

        <div class="">
            <a href="{{ forgotpassword }}">Forgot Password?</a>
        </div>
    </div>
<div class="form-content-left-div"> {{ pageContent }} </div>
<!--script>
    $(document).ready(function(){

        $('input#loginForm_Submit').on('click', function(){

            var email_1 = $('input#regMem_E1').val();
            //var passWd = $('input#regMem_Pw').val();

            if(!$(email_1).val()){
                alert(email_1);
            }
            /*if($.trim(email_1) !== '' && $_trim(passWd) !== ''){
                $.post('/login/process',
                    {regMem_E1: email_1},
                    {regMem_Pw: passWd},
                    function(data){
                   $('div#email-data').text(data);
                });
            }*/
        });
        /*function showHint(str) {
         if (str.length == 0) {
         document.getElementById("txtHint").innerHTML = "";
         return;
         } else {
         var xmlhttp = new XMLHttpRequest();
         xmlhttp.onreadystatechange = function() {
         if (this.readyState == 4 && this.status == 200) {
         document.getElementById("txtHint").innerHTML = this.responseText;
         }
         };
         xmlhttp.open("GET", "/appcms/profile/uploadbillboard=" + str, true);
         xmlhttp.send();
         }
         }*/
    });
</script-->
{% endblock %}