{% extends "template/layout/basetemplate.phtml" %}
{% block maincontent %}
    <div class = "main-content-tier1-wrapper" >
        <p> {{ pageContent }} </p >
        <p>
            <iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=hgdaffs72-20&marketplace=amazon&region=US&placement=B008A063QW&asins=B008A063QW&linkId=4318959d43343ad87d7758d9625d78e9&show_border=false&link_opens_in_new_window=false&price_color=333333&title_color=0066c0&bg_color=ffffff">
            </iframe>
        </p>
    </div >
{% endblock %}